### PR TITLE
Fix support for 3.11

### LINKED ISSUE #4: inspect.getargspec no longer available on Python 3.11
Hi Michael 

Thanks for setting up this fork.

I am trying to use this project, in an effort to stop using my personal fork of nose.

I can't get this to work with Python 3.11

I see that the GitHub Action job run with 3.11 is green - https://github.com/mdmintz/pynose/actions/runs/4867487327/jobs/8680119707

I guess  that the automated  tests don't do any package discovery

The error is

```
AttributeError: module 'inspect' has no attribute 'getargspec'`
```

```

$ ./build-py3/bin/pynose src/chevah_compat/tests/
E
======================================================================
ERROR: test suite for <module 'chevah_compat.tests' from '/home/adi/chevah/compat/src/chevah_compat/tests/__init__.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adi/chevah/compat/build-py3/lib/python3.11/site-packages/nose/suite.py", line 172, in run
    self.setUp()
  File "/home/adi/chevah/compat/build-py3/lib/python3.11/site-packages/nose/suite.py", line 247, in setUp
    self.setupContext(ancestor)
  File "/home/adi/chevah/compat/build-py3/lib/python3.11/site-packages/nose/suite.py", line 268, in setupContext
    try_run(context, names)
  File "/home/adi/chevah/compat/build-py3/lib/python3.11/site-packages/nose/util.py", line 416, in try_run
    args, varargs, varkw, defaults = inspect.getargspec(func)
                                     ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'

----------------------------------------------------------------------
Ran 0 tests in 0.001s

FAILED (errors=1)
```

I have something like this.

```
$ ./build-py3/bin/nosetests --version
nosetests version 1.4.4

$ ./build-py3/bin/pynose --version
pynose version 1.4.4

$ ./build-py3/bin/python --version
Python 3.11.3

$ cat build-py3/bin/pynose 
#!/home/adi/chevah/compat/build-py3/bin/python

from nose import main

if __name__ == '__main__':
    main()

$ cat /home/adi/chevah/compat/build-py3/lib/python3.11/site-packages/nose/__init__.py 
import sys
from nose.core import collector, main, run, run_exit, runmodule
from nose.exc import SkipTest, DeprecatedTest
from nose.tools import with_setup
from nose.__version__ import __version__
import collections

__author__ = 'Jason Pellerin (Original) / Michael Mintz (Update)'
version_list = [int(i) for i in __version__.split(".") if i.isdigit()]
__versioninfo__ = tuple(version_list)
__version__ = '.'.join(map(str, __versioninfo__))
__all__ = [
    'main', 'run', 'run_exit', 'runmodule', 'with_setup',
    'SkipTest', 'DeprecatedTest', 'collector'
]
if sys.version_info >= (3, 10):
    collections.Callable = collections.abc.Callable

```

### PR DESCRIPTION
**Pull request by adiroiban**
Fixes #4 

This updated the test suite for 3.11 and tries to fix any 3.11 isssue

### CODE REVIEW

**Comment by adiroiban** [comment]
I am waiting for CI to kick in and then I will push the fix and release notes changes

**Comment by mdmintz** [comment]
Already resolved by https://github.com/mdmintz/pynose/pull/6

Also, this PR is incorrectly titled, as it only changes tests... it does not actually resolve the issue. Will be keeping the tests as is to minimize the code of the repo.

**Comment by adiroiban** [comment]
Well... I had the other changes written on my local branch, but I haven't pushed those commits as I wanted to see the CI red.

I am a bit disappointed with having the fix merged without any automated tests.

But not a big deal. This is your repo so I am ok with this. No hard feelings.
